#Turtle: display a clock
import turtle

turtle.circle(100)
turtle.penup()
turtle.goto(90,100)
turtle.pendown()
turtle.write("3")
turtle.penup()
turtle.goto(0,185)
turtle.pendown()
turtle.write("12")
turtle.penup()
turtle.goto(-90,100)
turtle.pendown()
turtle.write("9")
turtle.penup()
turtle.goto(0,10)
turtle.pendown()
turtle.write("6")

turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.goto(60,100)
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.goto(0,160)
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.goto(-30,100)
turtle.penup()
turtle.goto(0,-20)
turtle.write("9:15:00")

turtle.done()